const Map<String, String> translationsEnUs = {
  'Error Occurred': 'Error Occurred',
  'Retry': 'Retry',
  'Connection still not established': 'Connection still not established',
  'Make sure your wifi or mobile data is connected, then press the retry button':
      'Make sure your wifi or mobile data is connected, then press the retry button',
  'Oops no internet connection': 'Oops no internet connection',
  'Searching location...': 'Searching location...',
  'Open settings': 'Open settings',
  'Sign in to continue!': 'Sign in to continue!',
  'Forgot Password': 'Forgot Password',
  'Sign In': 'Sign In',
  'or': 'or',
  'Email Address': 'Email Address',
  'Input Email Address': 'Input Email Address',
  'Email address cannot be empty': 'Email address cannot be empty',
  'Password': 'Password',
  'Input Password': 'Input Password',
  'Password cannot be empty': 'Password cannot be empty',
  'Sign In with ': 'Sign In with ',
  'Enter your email address to change your password':
      'Enter your email address to change your password',
  'Change Password': 'Change Password',
  'Input type cannot be empty': 'Input type cannot be empty',
  'Search': 'Search',
  'Available Promos': 'Available Promos',
  'All Menu': 'All Menu',
  'Food': 'Food',
  'Drink': 'Drink',
  'Home': 'Home',
  'Order': 'Order',
  'Profile': 'Profile',
  'Change': 'Change',
  'Change Language': 'Change Language',
  'Change PIN': 'Change PIN',
  'Email': 'Email',
  'Name': 'Name',
  'Phone Number': 'Phone Number',
  'Birth Date': 'Birth Date',
  'English': 'English',
  'Indonesia': 'Indonesia',
  ' Your have verified your ID card': ' Your have verified your ID card',
  'Verify your ID card now!': 'Verify your ID card now!',
  'Account Info': 'Account Info',
  'Discount Info': 'Discount Info',
  'You dont have discount': 'You dont have discount',
  'Oke': 'Oke',
  'Verify order': 'Verify order',
  'Press your fingerprint': 'Press your fingerprint',
  'Verify using PIN code': 'Verify using PIN code',
  'Add Notes': 'Add Notes',
  'Orders are being Prepared': 'Orders are being Prepared',
  'You can track your order in the ': 'You can track your order in the ',
  'Order Feature': 'Order Feature',
  'PIN wrong! n chances left.': 'PIN wrong! n chances left.',
  'Enter PIN code': 'Enter PIN code',
  'Total Order ': 'Total Order ',
  'Discount': 'Discount',
  'Voucher': 'Voucher',
  'You dont have voucher': 'You dont have voucher',
  'Choose Voucher': 'Choose Voucher',
  'Payment': 'Payment',
  'Pay Later': 'Pay Later',
  'Total Payment': 'Total Payment',
  'Order Now': 'Order Now',
  'Detail Voucher': 'Detail Voucher',
  'Expired Date': 'Expired Date',
  'Edit Menu': 'Edit Menu',
  'Save': 'Save',
  'Sorry you dont have voucher': 'Sorry you dont have voucher',
  'The use of vouchers cannot be combined with':
      'The use of vouchers cannot be combined with',
  'discount employee reward program': 'discount employee reward program',
  'Level': 'Level',
  'Notes': 'Notes',
  'Choose ': 'Choose ',
  'Sorry': 'Sorry',
  'No option available for ': 'No option available for ',
  'Price': 'Price',
  'Topping': 'Topping',
  'Detail Menu': 'Detail Menu',
  'Menu Name': 'Menu Name',
  'Add to Cart': 'Add to Cart',
  'In Queue': 'In Queue',
  'Being Prepared': 'Being Prepared',
  'Ready': 'Ready',
  'Done': 'Done',
  'Canceled': 'Canceled',
  'Give Review': 'Give Review',
  'Order Again': 'Order Again',
  'Ongoing': 'Ongoing',
  'History': 'History',
  'Your order is being prepared': 'Your order is being prepared',
  'Order Accepted': 'Order Accepted',
  'Take': 'Take',
  'Order Done': 'Order Done',
  'Confirmation': 'Confirmation',
  'Are you sure you want to cancel this order?':
      'Are you sure you want to cancel this order?',
  'Cancel': 'Cancel',
  'Yes': 'Yes',
  'Start making orders\nThe food you ordered will appear here so you can find your favorites again!':
      'Start making aorders\nThe food you ordered will appear here so you can find your favorites again!',
  'Already ordered?\nTrack your order here':
      'Already ordered?\nTrack your order here',
  'Name is required': 'Name is required',
  'PIN': 'PIN',
  'Ratings': 'Ratings',
  'Rating Now': 'Rating Now',
  'Other Info': 'Other Info',
  'Device Info': 'Device Info',
  'Version': 'Version',
  'Promo': 'Promo',
  'Promo Name': 'Promo Name',
  'Terms and Conditions': 'Terms and Conditions',
  'Enter the otp code that has been sent to the email':
      'Enter the otp code that has been sent to the email',
  'Incorrect OTP code': 'Incorrect OTP code',
  'Loading...': 'Loading...',
  'All Status': 'All Status',
  'Please authenticate to confirm order':
      'Please authenticate to confirm order',
  'Log Out': 'Log Out',
  'Error': 'Error',
  'Log Out Filed': 'Log Out Filed',
  'Privacy Policy': 'Privacy Policy',
  'Here': 'Here',
  'Add Menu to Cart Fisrt!': 'Add Menu to Cart Fisrt!',
  'Your Cart is Empty': 'Your Cart is Empty',
  'Shop Now': 'Shop Now',
};
