const Map<String, String> translationsEnUs = {
  'Profile': 'Profile',
  'Change': 'Change',
  'Change Language': 'Change Language',
  'Change PIN': 'Change PIN',
  'Email': 'Email',
  'Name': 'Name',
  'Phone Number': 'Phone Number',
  'Birth Date': 'Birth Date',
  'English': 'English',
  'Indonesia': 'Indonesia',
  ' Your have verified your ID card': ' Your have verified your ID card',
  'Verify your ID card now!': 'Verify your ID card now!',
  'Account info': 'Account info',
};
