const Map<String, String> translationsIdId = {
  'Error Occurred': 'Terjadi Kesalahan',
  'Retry': 'Coba Lagi',
  'Connection still not established': 'Koneksi masih belum tersambung',
  'Make sure your wifi or mobile data is connected, then press the retry button':
      'Pastikan wifi atau data seluler terhubung, lalu tekan tombol coba lagi',
  'Oops no internet connection': 'Oops Tidak ada koneksi internet',
  'Searching location...': 'Mencari lokasi...',
  'Open settings': 'Buka pengaturan',
  'Sign in to continue!': 'Masuk untuk melanjutkan!',
  'Forgot Password': 'Lupa Password',
  'Sign In': 'Masuk',
  'or': 'atau',
  'Email Address': 'Alamat Email',
  'Input Email Address': 'Masukkan Alamat Email',
  'Email address cannot be empty': 'Email tidak boleh kosong',
  'Password': 'Password',
  'Input Password': 'Masukkan Password',
  'Password cannot be empty': 'Password tidak boleh kosong',
  'Sign In with ': 'Masuk menggunakan ',
  'Enter your email address to change your password':
      'Masukkan alamat email untuk mengubah password anda',
  'Change Password': 'Ubah Password',
  'Input type cannot be empty': 'Input type tidak boleh kosong',
  'Search': 'Pencarian',
  'Available Promos': 'Promo yang Tersedia',
  'All Menu': 'Semua Menu',
  'Food': 'Makanan',
  'Drink': 'Minuman',
  'Home': 'Beranda',
  'Order': 'Pesanan',
  'Profile': 'Profil',
  'Change': 'Ubah',
  'Change Language': 'Ubah Bahasa',
  'Change PIN': 'Ubah PIN',
  'Email': 'Alamat Email',
  'Name': 'Nama',
  'Phone Number': 'No. Telepon',
  'Birth Date': 'Tanggal Lahir',
  'English': 'Inggris',
  'Indonesia': 'Indonesia',
  ' Your have verified your ID card': ' KTP anda sudah terverifikasi',
  'Verify your ID card now!': 'Verifikasi KTP mu sekarang!',
  'Account Info': 'Info Akun',
  'Discount Info': 'Info Diskon',
  'You dont have discount': 'Anda tidak memiliki diskon',
  'Oke': 'Oke',
  'Verify order': 'Verifikasi pesanan',
  'Press your fingerprint': 'Tekan sidik jari anda',
  'Verify using PIN code': 'Verifikasi menggunakan PIN',
  'Add Notes': 'Tambahkan Catatan',
  'Orders are being Prepared': 'Pesanan Sedang Disiapkan',
  'You can track your order in the ': 'Kamu dapat melacak pesananmu di fitur ',
  'Order Feature': 'Pesanan',
  'PIN wrong! n chances left.': 'PIN salah! n percobaan lagi.',
  'Enter PIN code': 'Masukkan PIN',
  'Total Order ': 'Total Pesanan ',
  'Discount': 'Diskon',
  'Voucher': 'Voucher',
  'You dont have voucher': 'Anda tidak memiliki voucher',
  'Choose Voucher': 'Pilih Voucher',
  'Payment': 'Pembayaran',
  'Pay Later': 'Bayar Nanti',
  'Total Payment': 'Total Pembayaran',
  'Order Now': 'Pesan Sekarang',
  'Detail Voucher': 'Detail Voucher',
  'Expired Date': 'Tanggal Kadaluwarsa',
  'Edit Menu': 'Edit Menu',
  'Save': 'Simpan',
  'Sorry you dont have voucher': 'Maaf anda tidak memiliki voucher',
  'The use of vouchers cannot be combined with':
      'Penggunaan voucher tidak dapat digabung dengan',
  'discount employee reward program': 'diskon program penghargaan karyawan',
  'Level': 'Level',
  'Notes': 'Catatan',
  'Choose ': 'Pilih ',
  'Sorry': 'Maaf',
  'No option available for ': 'Tidak tersedia pilihan ',
  'Price': 'Harga',
  'Topping': 'Toping',
  'Detail Menu': 'Detail Menu',
  'Menu Name': 'Nama Menu',
  'Add to Cart': 'Tambahkan ke Keranjang',
  'In Queue': 'Dalam antrian',
  'Being Prepared': 'Sedang Disiapkan',
  'Ready': 'Siap',
  'Done': 'Selesai',
  'Canceled': 'Dibatalkan',
  'Give Review': 'Berikan Penilaian',
  'Order Again': 'Pesan Lagi',
  'Ongoing': 'Sedang Berjalan',
  'History': 'Riwayat',
  'Your order is being prepared': 'Pesanan kamu sedang disiapkan',
  'Order Accepted': 'Pesanan Diterima',
  'Take': 'Silakan Diambil',
  'Order Done': 'Pesanan Selesai',
  'Confirmation': 'Konfirmasi',
  'Are you sure you want to cancel this order?':
      'Apakah Anda yakin ingin membatalkan pesanan ini?',
  'Cancel': 'Batal',
  'Yes': 'Ya',
  'Start making orders\nThe food you ordered will appear here so you can find your favorites again!':
      'Mulai buat pesanan\nMakanan yang kamu pesan akan muncul di sini agar kamu bisa menemukan menu favoritmu lagi!',
  'Already ordered?\nTrack your order here':
      'Sudah Pesan?\nLacak Pesananmu di sini',
  'Name is required': 'Nama harus diisi',
  'PIN': 'PIN',
  'Ratings': 'Penilaian',
  'Rating Now': 'Nilai Sekarang',
  'Other Info': 'Info Lainnya',
  'Device Info': 'Info Perangkat',
  'Version': 'Versi',
  'Promo': 'Promo',
  'Promo Name': 'Nama Promo',
  'Terms and Conditions': 'Syarat dan Ketentuan',
  'Enter the otp code that has been sent to the email':
      'Masukkan kode otp yang telah dikirimkan ke email',
  'Incorrect OTP code': 'Kode OTP salah',
  'Loading...': 'Sedang diproses...',
  'All Status': 'Semua Status',
  'Please authenticate to confirm order':
      'Harap lakukan autentikasi untuk mengonfirmasi pesanan'
};
