const Map<String, String> translationsIdId = {
  'Profile': 'Profil',
  'Change': 'Ubah',
  'Change Language': 'Ubah Bahasa',
  'Change PIN': 'Ubah PIN',
  'Email': 'Alamat Email',
  'Name': 'Nama',
  'Phone Number': 'No. Telepon',
  'Birth Date': 'Tanggal Lahir',
  'English': 'Inggris',
  'Indonesia': 'Indonesia',
  ' Your have verified your ID card': ' KTP anda sudah terverifikasi',
  'Verify your ID card now!': 'Verifikasi KTP mu sekarang!',
  'Account info': 'Info Akun',
};
