// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzcp7s9QT9lTkJNYiZXC7JfUI8buGqAp8',
    appId: '1:207269428309:web:d9499613225ed4083fe8dc',
    messagingSenderId: '207269428309',
    projectId: 'trainee-venturo',
    authDomain: 'trainee-venturo.firebaseapp.com',
    storageBucket: 'trainee-venturo.appspot.com',
    measurementId: 'G-8C344E3PVC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDH6iLHA_c6OfrnKJsZd9xp7Y5MmqpBXG0',
    appId: '1:207269428309:android:a34a0c3fee1b11d43fe8dc',
    messagingSenderId: '207269428309',
    projectId: 'trainee-venturo',
    storageBucket: 'trainee-venturo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvTqal40Fq-wYPu_4neM_Pq6ipdc_W3p0',
    appId: '1:207269428309:ios:2a887c5ef359cba93fe8dc',
    messagingSenderId: '207269428309',
    projectId: 'trainee-venturo',
    storageBucket: 'trainee-venturo.appspot.com',
    iosClientId: '207269428309-g8ch7cnqen0hu8sjlmio3pkhcuk6m8bn.apps.googleusercontent.com',
    iosBundleId: 'com.core.venturo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvTqal40Fq-wYPu_4neM_Pq6ipdc_W3p0',
    appId: '1:207269428309:ios:2a887c5ef359cba93fe8dc',
    messagingSenderId: '207269428309',
    projectId: 'trainee-venturo',
    storageBucket: 'trainee-venturo.appspot.com',
    iosClientId: '207269428309-g8ch7cnqen0hu8sjlmio3pkhcuk6m8bn.apps.googleusercontent.com',
    iosBundleId: 'com.core.venturo',
  );
}
